class VietnamAddresses {
  // Danh sách tỉnh/thành phố
  static const List<String> provinces = [
    'An Giang',
    'Bà Rịa - Vũng Tàu',
    'Bạc Liêu',
    'Bắc Giang',
    'Bắc Kạn',
    'Bắc Ninh',
    'Bến Tre',
    'Bình Định',
    'Bình Dương',
    'Bình Phước',
    'Bình Thuận',
    'Cà Mau',
    'Cao Bằng',
    'Cần Thơ',
    'Đà Nẵng',
    'Đắk Lắk',
    'Đắk Nông',
    'Điện Biên',
    'Đồng Nai',
    'Đồng Tháp',
    'Gia Lai',
    'Hà Giang',
    'Hà Nam',
    'Hà Nội',
    'Hà Tĩnh',
    'Hải Dương',
    'Hải Phòng',
    'Hậu Giang',
    'Hòa Bình',
    'Hưng Yên',
    'Khánh Hòa',
    'Kiên Giang',
    'Kon Tum',
    'Lai Châu',
    'Lâm Đồng',
    'Lạng Sơn',
    'Lào Cai',
    'Long An',
    'Nam Định',
    'Nghệ An',
    'Ninh Bình',
    'Ninh Thuận',
    'Phú Thọ',
    'Phú Yên',
    'Quảng Bình',
    'Quảng Nam',
    'Quảng Ngãi',
    'Quảng Ninh',
    'Quảng Trị',
    'Sóc Trăng',
    'Sơn La',
    'Tây Ninh',
    'Thái Bình',
    'Thái Nguyên',
    'Thanh Hóa',
    'Thừa Thiên Huế',
    'Tiền Giang',
    'TP. Hồ Chí Minh',
    'Trà Vinh',
    'Tuyên Quang',
    'Vĩnh Long',
    'Vĩnh Phúc',
    'Yên Bái',
  ];

  // Mapping tỉnh/thành phố -> quận/huyện
  static const Map<String, List<String>> districts = {
    'Hà Nội': [
      'Ba Đình',
      'Hoàn Kiếm',
      'Tây Hồ',
      'Long Biên',
      'Cầu Giấy',
      'Đống Đa',
      'Hai Bà Trưng',
      'Hoàng Mai',
      'Thanh Xuân',
      'Sóc Sơn',
      'Đông Anh',
      'Gia Lâm',
      'Nam Từ Liêm',
      'Bắc Từ Liêm',
      'Mê Linh',
      'Hà Đông',
      'Sơn Tây',
      'Ba Vì',
      'Phúc Thọ',
      'Đan Phượng',
      'Hoài Đức',
      'Quốc Oai',
      'Thạch Thất',
      'Chương Mỹ',
      'Thanh Oai',
      'Thường Tín',
      'Phú Xuyên',
      'Ứng Hòa',
      'Mỹ Đức',
    ],
    'TP. Hồ Chí Minh': [
      'Quận 1',
      'Quận 2',
      'Quận 3',
      'Quận 4',
      'Quận 5',
      'Quận 6',
      'Quận 7',
      'Quận 8',
      'Quận 9',
      'Quận 10',
      'Quận 11',
      'Quận 12',
      'Bình Thạnh',
      'Tân Bình',
      'Tân Phú',
      'Phú Nhuận',
      'Gò Vấp',
      'Bình Tân',
      'Tân Uyên',
      'Củ Chi',
      'Hóc Môn',
      'Bình Chánh',
      'Nhà Bè',
      'Cần Giờ',
    ],
    'Đà Nẵng': [
      'Hải Châu',
      'Thanh Khê',
      'Sơn Trà',
      'Ngũ Hành Sơn',
      'Liên Chiểu',
      'Cẩm Lệ',
      'Hòa Vang',
      'Hoàng Sa',
    ],
    'Cần Thơ': [
      'Ninh Kiều',
      'Ô Môn',
      'Bình Thủy',
      'Cái Răng',
      'Thốt Nốt',
      'Vĩnh Thạnh',
      'Cờ Đỏ',
      'Phong Điền',
      'Thới Lai',
    ],
    'Hải Phòng': [
      'Hồng Bàng',
      'Ngô Quyền',
      'Lê Chân',
      'Hải An',
      'Kiến An',
      'Đồ Sơn',
      'Dương Kinh',
      'Thuỷ Nguyên',
      'An Dương',
      'An Lão',
      'Kiến Thuỵ',
      'Tiên Lãng',
      'Vĩnh Bảo',
      'Cát Hải',
      'Bạch Long Vĩ',
    ],
    'An Giang': [
      'Long Xuyên',
      'Châu Đốc',
      'An Phú',
      'Châu Phú',
      'Châu Thành',
      'Chợ Mới',
      'Phú Tân',
      'Tân Châu',
      'Thoại Sơn',
      'Tri Tôn',
      'Tịnh Biên',
    ],
    'Bà Rịa - Vũng Tàu': [
      'Vũng Tàu',
      'Bà Rịa',
      'Châu Đức',
      'Côn Đảo',
      'Đất Đỏ',
      'Long Điền',
      'Tân Thành',
      'Xuyên Mộc',
    ],
    'Bình Dương': [
      'Thủ Dầu Một',
      'Dầu Tiếng',
      'Bến Cát',
      'Tân Uyên',
      'Dĩ An',
      'Thuận An',
      'Bàu Bàng',
      'Bắc Tân Uyên',
      'Phú Giáo',
    ],
    'Đồng Nai': [
      'Biên Hòa',
      'Long Khánh',
      'Cẩm Mỹ',
      'Định Quán',
      'Long Thành',
      'Nhơn Trạch',
      'Tân Phú',
      'Vĩnh Cửu',
      'Xuân Lộc',
      'Thống Nhất',
      'Trảng Bom',
    ],
    'Khánh Hòa': [
      'Nha Trang',
      'Cam Ranh',
      'Cam Lâm',
      'Diên Khánh',
      'Khánh Sơn',
      'Khánh Vĩnh',
      'Ninh Hòa',
      'Trường Sa',
      'Vạn Ninh',
    ],
    'Bạc Liêu': [
      'Bạc Liêu',
      'Hồng Dân',
      'Phước Long',
      'Vĩnh Lợi',
      'Giá Rai',
      'Đông Hải',
      'Hoà Bình',
    ],
    'Bắc Giang': [
      'Bắc Giang',
      'Yên Thế',
      'Tân Yên',
      'Lạng Giang',
      'Lục Nam',
      'Lục Ngạn',
      'Sơn Động',
      'Yên Dũng',
      'Việt Yên',
      'Hiệp Hòa',
    ],
    'Bắc Kạn': [
      'Bắc Kạn',
      'Pác Nặm',
      'Ba Bể',
      'Ngân Sơn',
      'Bạch Thông',
      'Chợ Đồn',
      'Chợ Mới',
      'Na Rì',
    ],
    'Bắc Ninh': [
      'Bắc Ninh',
      'Yên Phong',
      'Quế Võ',
      'Tiên Du',
      'Từ Sơn',
      'Thị xã Từ Sơn',
      'Gia Bình',
      'Lương Tài',
    ],
    'Bến Tre': [
      'Thành phố Bến Tre',
      'Châu Thành',
      'Chợ Lách',
      'Mỏ Cày Bắc',
      'Mỏ Cày Nam',
      'Giồng Trôm',
      'Bình Đại',
      'Ba Tri',
      'Thạnh Phú',
    ],
    'Bình Định': [
      'Quy Nhon',
      'An Lão',
      'Hoài Nhơn',
      'Hoài Ân',
      'Phù Mỹ',
      'Vĩnh Thạnh',
      'Tây Sơn',
      'Phù Cát',
      'Tuy Phước',
    ],
    'Bình Phước': [
      'Đồng Xoài',
      'Bình Long',
      'Bù Đăng',
      'Bù Đốp',
      'Bù Gia Mập',
      'Chơn Thành',
      'Đồng Phú',
      'Hớn Quản',
      'Lộc Ninh',
    ],
    'Bình Thuận': [
      'Phan Thiết',
      'La Gi',
      'Tuy Phong',
      'Bắc Bình',
      'Hàm Thuận Bắc',
      'Hàm Thuận Nam',
      'Tánh Linh',
      'Đức Linh',
      'Phú Quí',
    ],
    'Cà Mau': [
      'Cà Mau',
      'U Minh',
      'Thới Bình',
      'Trần Văn Thời',
      'Cái Nước',
      'Đầm Dơi',
      'Ngọc Hiển',
      'Năm Căn',
      'Phú Tân',
    ],
    'Cao Bằng': [
      'Cao Bằng',
      'Bảo Lạc',
      'Bảo Lâm',
      'Hạ Lang',
      'Hà Quảng',
      'Hoà An',
      'Nguyên Bình',
      'Quảng Uyên',
      'Thạch An',
      'Trùng Khánh',
    ],
    'Đắk Lắk': [
      'Buôn Ma Thuột',
      'Buôn Hồ',
      'Ea H\'leo',
      'Ea Súp',
      'Buôn Đôn',
      'Cư M\'gar',
      'Krông Búk',
      'Krông Năng',
      'Krông A Na',
      'Krông Bông',
      'Krông Pắk',
      'Krông Nô',
      'Lắk',
      'M\'Đrắk',
    ],
    'Đắk Nông': [
      'Gia Nghĩa',
      'Cư Jút',
      'Đắk Mil',
      'Đắk R\'Lấp',
      'Đắk Song',
      'Đắk Glong',
      'Tuy Đức',
      'Krông Nô',
    ],
    'Điện Biên': [
      'Điện Biên Phủ',
      'Mường Lay',
      'Mường Nhé',
      'Mường Chà',
      'Tủa Chùa',
      'Tuần Giáo',
      'Điện Biên',
      'Điện Biên Đông',
      'Mường Ảng',
      'Nậm Pồ',
    ],
    'Đồng Tháp': [
      'Cao Lãnh',
      'Sa Đéc',
      'Tam Nông',
      'Tân Hồng',
      'Tân Hưng',
      'Thanh Bình',
      'Tháp Mười',
      'Lấp Vò',
      'Lai Vung',
      'Châu Thành',
      'Hồng Ngự',
    ],
    'Gia Lai': [
      'Pleiku',
      'An Khê',
      'Ayun Pa',
      'KBang',
      'Đăk Đoa',
      'Chư Păh',
      'Chư Prông',
      'Chư Sê',
      'Đăk Pơ',
      'Đức Cơ',
      'Ia Grai',
      'Ia Pa',
      'KBang',
      'Kông Chro',
      'Krông Pa',
      'Mang Yang',
      'Phú Thiện',
    ],
    'Hà Giang': [
      'Hà Giang',
      'Đồng Văn',
      'Mèo Vạc',
      'Yên Minh',
      'Quản Bạ',
      'Bắc Mê',
      'Hoàng Su Phì',
      'Xín Mần',
      'Bắc Quang',
      'Quang Bình',
      'Vị Xuyên',
    ],
    'Hà Nam': [
      'Phủ Lý',
      'Duy Tiên',
      'Kim Bảng',
      'Lý Nhân',
      'Thanh Liêm',
      'Bình Lục',
    ],
    'Hà Tĩnh': [
      'Hà Tĩnh',
      'Hồng Lĩnh',
      'Hương Sơn',
      'Đức Thọ',
      'Vũ Quang',
      'Nghi Xuân',
      'Can Lộc',
      'Hương Khê',
      'Thạch Hà',
      'Cẩm Xuyên',
      'Kỳ Anh',
      'Lộc Hà',
    ],
    'Hải Dương': [
      'Hải Dương',
      'Chí Linh',
      'Nam Sách',
      'Kinh Môn',
      'Kim Thành',
      'Thanh Hà',
      'Cẩm Giàng',
      'Bình Giang',
      'Gia Lộc',
      'Tứ Kỳ',
      'Ninh Giang',
      'Thanh Miện',
    ],
    'Hậu Giang': [
      'Vị Thanh',
      'Ngã Bảy',
      'Châu Thành',
      'Châu Thành A',
      'Phụng Hiệp',
      'Vị Thủy',
      'Long Mỹ',
      'Long Mỹ',
    ],
    'Hòa Bình': [
      'Hòa Bình',
      'Đà Bắc',
      'Lương Sơn',
      'Kim Bôi',
      'Cao Phong',
      'Tân Lạc',
      'Mai Châu',
      'Đạp Đa',
      'Yên Thủy',
      'Lạc Sơn',
      'Lạc Thủy',
    ],
    'Hưng Yên': [
      'Hưng Yên',
      'Văn Lâm',
      'Văn Giang',
      'Yên Mỹ',
      'Mỹ Hào',
      'Ân Thi',
      'Khoái Châu',
      'Kim Động',
      'Tiên Lữ',
      'Phù Cừ',
    ],
    'Kiên Giang': [
      'Rạch Giá',
      'Hà Tiên',
      'Kiên Lương',
      'Hòn Đất',
      'Tân Hiệp',
      'Châu Thành',
      'Giồng Riềng',
      'Gò Quao',
      'An Biên',
      'An Minh',
      'Vĩnh Thuận',
      'Phú Quốc',
      'Kiên Hải',
      'U Minh Thượng',
    ],
    'Kon Tum': [
      'Kon Tum',
      'Đắk Glei',
      'Đắk Hà',
      'Đắk Tô',
      'Ia H\'Drai',
      'Kon Plông',
      'Kon Rẫy',
      'Ngọc Hồi',
      'Sa Thầy',
      'Tu Mơ Rông',
    ],
    'Lai Châu': [
      'Lai Châu',
      'Tam Đường',
      'Mường Tè',
      'Sìn Hồ',
      'Phong Thổ',
      'Than Uyên',
      'Tân Uyên',
      'Nậm Nhùn',
    ],
    'Lâm Đồng': [
      'Đà Lạt',
      'Bảo Lộc',
      'Đam Rông',
      'Lạc Dương',
      'Lâm Hà',
      'Đơn Dương',
      'Đức Trọng',
      'Cát Tiên',
      'Bảo Lâm',
    ],
    'Lạng Sơn': [
      'Lạng Sơn',
      'Tràng Định',
      'Bình Gia',
      'Văn Lãng',
      'Cao Lộc',
      'Văn Quan',
      'Bắc Sơn',
      'Hữu Lũng',
      'Chi Lăng',
      'Lộc Bình',
      'Đình Lập',
    ],
    'Lào Cai': [
      'Lào Cai',
      'Bát Xát',
      'Mường Khương',
      'Si Ma Cai',
      'Bắc Hà',
      'Bảo Thắng',
      'Bảo Yên',
      'Sa Pa',
      'Văn Bàn',
    ],
    'Long An': [
      'Tân An',
      'Kiến Tường',
      'Tân Hưng',
      'Vĩnh Hưng',
      'Mộc Hóa',
      'Tân Thạnh',
      'Thạnh Hóa',
      'Đức Huệ',
      'Đức Hòa',
      'Bến Lức',
      'Thủ Thừa',
      'Tân Trụ',
      'Cần Đước',
      'Cần Giuộc',
      'Châu Thành',
    ],
    'Nam Định': [
      'Nam Định',
      'Mỹ Lộc',
      'Vụ Bản',
      'Ý Yên',
      'Nghĩa Hưng',
      'Nam Trực',
      'Trực Ninh',
      'Xuân Trường',
      'Giao Thủy',
      'Hải Hậu',
    ],
    'Nghệ An': [
      'Vinh',
      'Cửa Lò',
      'Thái Hòa',
      'Quế Phong',
      'Quỳ Châu',
      'Kỳ Sơn',
      'Tương Dương',
      'Nghĩa Đàn',
      'Quỳ Hợp',
      'Quỳnh Lưu',
      'Con Cuông',
      'Tân Kỳ',
      'Anh Sơn',
      'Diễn Châu',
      'Yên Thành',
      'Đô Lương',
      'Thanh Chương',
      'Nghi Lộc',
      'Nam Đàn',
      'Hưng Nguyên',
    ],
    'Ninh Bình': [
      'Ninh Bình',
      'Tam Điệp',
      'Nho Quan',
      'Gia Viễn',
      'Hoa Lư',
      'Yên Khánh',
      'Kim Sơn',
      'Yên Mô',
    ],
    'Ninh Thuận': [
      'Phan Rang - Tháp Chàm',
      'Bác Ái',
      'Ninh Sơn',
      'Ninh Hải',
      'Ninh Phước',
      'Thuận Bắc',
      'Thuận Nam',
    ],
    'Phú Thọ': [
      'Việt Trì',
      'Phú Thọ',
      'Đoan Hùng',
      'Hạ Hòa',
      'Thanh Ba',
      'Phù Ninh',
      'Yên Lập',
      'Cẩm Khê',
      'Tam Nông',
      'Lâm Thao',
      'Thanh Sơn',
      'Thanh Thủy',
      'Tân Sơn',
    ],
    'Phú Yên': [
      'Tuy Hòa',
      'Sông Cầu',
      'Đồng Xuân',
      'Tuy An',
      'Sơn Hòa',
      'Sông Hinh',
      'Tây Hòa',
      'Phú Hòa',
    ],
    'Quảng Bình': [
      'Đồng Hới',
      'Minh Hóa',
      'Tuyên Hóa',
      'Quảng Trạch',
      'Bố Trạch',
      'Quảng Ninh',
      'Lệ Thủy',
    ],
    'Quảng Nam': [
      'Tam Kỳ',
      'Hội An',
      'Tây Giang',
      'Đông Giang',
      'Đại Lộc',
      'Điện Bàn',
      'Duy Xuyên',
      'Quế Sơn',
      'Nam Giang',
      'Phước Sơn',
      'Hiệp Đức',
      'Thăng Bình',
      'Tiên Phước',
      'Bắc Trà My',
      'Nam Trà My',
      'Phú Ninh',
      'Núi Thành',
    ],
    'Quảng Ngãi': [
      'Quảng Ngãi',
      'Ba Tơ',
      'Bình Sơn',
      'Đức Phổ',
      'Lý Sơn',
      'Minh Long',
      'Mộ Đức',
      'Nghĩa Hành',
      'Sơn Hà',
      'Sơn Tịnh',
      'Sơn Tây',
      'Tây Trà',
      'Trà Bồng',
      'Tư Nghĩa',
    ],
    'Quảng Ninh': [
      'Hạ Long',
      'Móng Cái',
      'Cẩm Phả',
      'Uông Bí',
      'Bình Liêu',
      'Tiên Yên',
      'Đầm Hà',
      'Hải Hà',
      'Ba Chẽ',
      'Vân Đồn',
      'Hoành Bồ',
      'Đông Triều',
      'Quảng Yên',
      'Cô Tô',
    ],
    'Quảng Trị': [
      'Đông Hà',
      'Quảng Trị',
      'Vĩnh Linh',
      'Hướng Hóa',
      'Gio Linh',
      'Đa Krông',
      'Cam Lộ',
      'Triệu Phong',
      'Hải Lăng',
    ],
    'Sóc Trăng': [
      'Sóc Trăng',
      'Châu Thành',
      'Kế Sách',
      'Mỹ Tú',
      'Cù Lao Dung',
      'Long Phú',
      'Mỹ Xuyên',
      'Ngã Năm',
      'Thạnh Trị',
      'Vĩnh Châu',
      'Trần Đề',
    ],
    'Sơn La': [
      'Sơn La',
      'Quỳnh Nhai',
      'Mường La',
      'Thuận Châu',
      'Mường Chà',
      'Sông Mã',
      'Sốp Cộp',
      'Yên Châu',
      'Mai Sơn',
      'Mộc Châu',
      'Mường Sơn',
      'Sông Mã',
      'Sốp Cộp',
      'Vân Hồ',
    ],
    'Tây Ninh': [
      'Tây Ninh',
      'Tân Biên',
      'Tân Châu',
      'Dương Minh Châu',
      'Châu Thành',
      'Hòa Thành',
      'Bến Cầu',
      'Gò Dầu',
      'Trảng Bàng',
    ],
    'Thái Bình': [
      'Thái Bình',
      'Quỳnh Phụ',
      'Hưng Hà',
      'Đông Hưng',
      'Thái Thụy',
      'Tiền Hải',
      'Kiến Xương',
      'Vũ Thư',
    ],
    'Thái Nguyên': [
      'Thái Nguyên',
      'Sông Công',
      'Định Hóa',
      'Phú Lương',
      'Đồng Hỷ',
      'Võ Nhai',
      'Đại Từ',
      'Phú Bình',
      'Phổ Yên',
    ],
    'Thanh Hóa': [
      'Thanh Hóa',
      'Bỉm Sơn',
      'Sầm Sơn',
      'Mường Lát',
      'Quan Hóa',
      'Bá Thước',
      'Quan Sơn',
      'Lang Chánh',
      'Ngọc Lặc',
      'Cẩm Thủy',
      'Thạch Thành',
      'Hà Trung',
      'Vĩnh Lộc',
      'Yên Định',
      'Thọ Xuân',
      'Thường Xuân',
      'Triệu Sơn',
      'Thiệu Hóa',
      'Hoằng Hóa',
      'Hậu Lộc',
      'Nga Sơn',
      'Như Xuân',
      'Như Thanh',
      'Nông Cống',
      'Đông Sơn',
      'Quảng Xương',
      'Tĩnh Gia',
    ],
    'Thừa Thiên Huế': [
      'Huế',
      'Hương Thủy',
      'Hương Trà',
      'A Lưới',
      'Phong Điền',
      'Quảng Điền',
      'Phú Vang',
      'Phú Lộc',
      'Nam Đông',
    ],
    'Tiền Giang': [
      'Mỹ Tho',
      'Gò Công',
      'Cai Lậy',
      'Tân Phú Đông',
      'Cái Bè',
      'Châu Thành',
      'Chợ Gạo',
      'Gò Công Tây',
      'Gò Công Đông',
      'Tân Phước',
    ],
    'Trà Vinh': [
      'Trà Vinh',
      'Càng Long',
      'Cầu Kè',
      'Tiểu Cần',
      'Châu Thành',
      'Cầu Ngang',
      'Trà Cú',
      'Duyên Hải',
    ],
    'Tuyên Quang': [
      'Tuyên Quang',
      'Lâm Bình',
      'Na Hang',
      'Chiêm Hóa',
      'Hàm Yên',
      'Yên Sơn',
      'Sơn Dương',
    ],
    'Vĩnh Long': [
      'Vĩnh Long',
      'Long Hồ',
      'Mang Thít',
      'Vũng Liêm',
      'Tam Bình',
      'Bình Minh',
      'Trà Ôn',
      'Bình Tân',
    ],
    'Vĩnh Phúc': [
      'Vĩnh Yên',
      'Phúc Yên',
      'Lập Thạch',
      'Tam Dương',
      'Tam Đảo',
      'Bình Xuyên',
      'Yên Lạc',
      'Vĩnh Tường',
      'Sông Lô',
    ],
    'Yên Bái': [
      'Yên Bái',
      'Nghĩa Lộ',
      'Lục Yên',
      'Văn Yên',
      'Mù Cang Chải',
      'Trấn Yên',
      'Trạm Tấu',
      'Văn Chấn',
      'Yên Bình',
    ],
  };

  // Mapping quận/huyện -> phường/xã (ví dụ cho một số quận/huyện chính)
  static const Map<String, List<String>> wards = {
    'Ba Đình': [
      'Phúc Xá',
      'Trúc Bạch',
      'Vĩnh Phúc',
      'Cống Vị',
      'Liễu Giai',
      'Ngọc Hà',
      'Đội Cấn',
      'Ngọc Khánh',
      'Kim Mã',
      'Giảng Võ',
      'Quán Thánh',
      'Thành Công',
      'Điện Biên',
      'Đội Nhân',
      'Nguyễn Trung Trực',
    ],
    'Hoàn Kiếm': [
      'Phúc Tân',
      'Đồng Xuân',
      'Hàng Mã',
      'Hàng Buồm',
      'Hàng Đào',
      'Hàng Bồ',
      'Cửa Đông',
      'Lý Thái Tổ',
      'Phan Chu Trinh',
      'Hàng Bạc',
      'Hàng Gai',
      'Chương Dương',
      'Hàng Trống',
      'Cửa Nam',
      'Hàng Bông',
      'Tràng Tiền',
      'Trần Hưng Đạo',
    ],
    'Quận 1': [
      'Bến Nghé',
      'Đa Kao',
      'Bến Thành',
      'Nguyễn Thái Bình',
      'Phạm Ngũ Lão',
      'Cầu Ông Lãnh',
      'Cô Giang',
      'Nguyễn Cư Trinh',
      'Cầu Kho',
      'Tân Định',
      'Đa Kao',
      'Bến Nghé',
    ],
    'Hải Châu': [
      'Hải Châu I',
      'Hải Châu II',
      'Hòa Cường Bắc',
      'Hòa Cường Nam',
      'Hòa Thuận Đông',
      'Hòa Thuận Tây',
      'Nam Dương',
      'Phước Ninh',
      'Thạch Thang',
      'Thanh Bình',
      'Thuận Phước',
    ],
    'Cầu Giấy': [
      'Nghĩa Đô',
      'Nghĩa Tân',
      'Mai Dịch',
      'Dịch Vọng',
      'Dịch Vọng Hậu',
      'Quan Hoa',
      'Yên Hòa',
      'Trung Hòa',
    ],
    'Đống Đa': [
      'Cát Linh',
      'Văn Miếu',
      'Quốc Tử Giám',
      'Láng Thượng',
      'Ô Chợ Dừa',
      'Văn Chương',
      'Hàng Bột',
      'Láng Hạ',
      'Khâm Thiên',
      'Thổ Quan',
      'Nam Đồng',
      'Trung Phụng',
      'Trung Liệt',
      'Phương Liên',
      'Thịnh Quang',
      'Trung Tự',
      'Kim Liên',
      'Phương Mai',
      'Ngã Tư Sở',
      'Khương Thượng',
    ],
    'Hai Bà Trưng': [
      'Phạm Đình Hổ',
      'Lê Đại Hành',
      'Đồng Nhân',
      'Phố Huế',
      'Đống Mác',
      'Thanh Lương',
      'Thanh Nhàn',
      'Cầu Dền',
      'Bách Khoa',
      'Đồng Tâm',
      'Vĩnh Tuy',
      'Bạch Mai',
      'Quỳnh Mai',
      'Quỳnh Lôi',
      'Minh Khai',
      'Trương Định',
    ],
    'Hoàng Mai': [
      'Giáp Bát',
      'Vĩnh Hưng',
      'Định Công',
      'Mai Động',
      'Tương Mai',
      'Thanh Trì',
      'Vĩnh Hưng',
      'Hoàng Văn Thụ',
      'Yên Sở',
      'Nhân Chính',
      'Thịnh Liệt',
      'Trần Phú',
      'Tân Mai',
      'Tứ Hiệp',
      'Yên Viên',
      'Đại Kim',
      'Định Công',
      'Hoàng Liệt',
      'Vĩnh Quỳnh',
    ],
    'Quận 2': [
      'Thảo Điền',
      'An Phú',
      'Bình An',
      'Bình Khánh',
      'Bình Trưng Đông',
      'Bình Trưng Tây',
      'Cát Lái',
      'An Khánh',
      'Thủ Thiêm',
    ],
    'Quận 3': [
      'Phường 1',
      'Phường 2',
      'Phường 3',
      'Phường 4',
      'Phường 5',
      'Phường 6',
      'Phường 7',
      'Phường 8',
      'Phường 9',
      'Phường 10',
      'Phường 11',
      'Phường 12',
      'Phường 13',
      'Phường 14',
    ],
    'Quận 7': [
      'Tân Thuận Đông',
      'Tân Thuận Tây',
      'Tân Kiểng',
      'Tân Hưng',
      'Bình Thuận',
      'Tân Quy',
      'Phú Thuận',
      'Tân Phong',
      'Tân Phú',
      'Tân Hưng',
    ],
    'Bình Thạnh': [
      'Phường 1',
      'Phường 2',
      'Phường 3',
      'Phường 4',
      'Phường 5',
      'Phường 6',
      'Phường 7',
      'Phường 8',
      'Phường 9',
      'Phường 10',
      'Phường 11',
      'Phường 12',
      'Phường 13',
      'Phường 14',
      'Phường 15',
      'Phường 16',
      'Phường 17',
      'Phường 18',
      'Phường 19',
      'Phường 20',
      'Phường 21',
      'Phường 22',
      'Phường 23',
      'Phường 24',
      'Phường 25',
      'Phường 26',
      'Phường 27',
      'Phường 28',
    ],
    'Tân Bình': [
      'Phường 1',
      'Phường 2',
      'Phường 3',
      'Phường 4',
      'Phường 5',
      'Phường 6',
      'Phường 7',
      'Phường 8',
      'Phường 9',
      'Phường 10',
      'Phường 11',
      'Phường 12',
      'Phường 13',
      'Phường 14',
      'Phường 15',
    ],
    'Gò Vấp': [
      'Phường 1',
      'Phường 2',
      'Phường 3',
      'Phường 4',
      'Phường 5',
      'Phường 6',
      'Phường 7',
      'Phường 8',
      'Phường 9',
      'Phường 10',
      'Phường 11',
      'Phường 12',
      'Phường 13',
      'Phường 14',
      'Phường 15',
      'Phường 16',
      'Phường 17',
    ],
    'Thanh Khê': [
      'Thanh Khê Đông',
      'Thanh Khê Tây',
      'Xuân Hà',
      'Tân Chính',
      'Chính Gián',
      'Vĩnh Trung',
      'Thạc Gián',
      'An Khê',
      'Hòa Khê',
    ],
    'Sơn Trà': [
      'An Hải Bắc',
      'An Hải Đông',
      'An Hải Tây',
      'Mân Thái',
      'Nại Hiên Đông',
      'Phước Mỹ',
      'Thọ Quang',
      'An Hải Nam',
    ],
    'Ninh Kiều': [
      'Cái Khế',
      'An Hòa',
      'Thới Bình',
      'An Nghiệp',
      'An Cư',
      'An Hội',
      'An Thới',
      'Cái Răng',
      'Xuân Khánh',
      'Hưng Lợi',
      'An Khánh',
      'An Bình',
    ],
    'Biên Hòa': [
      'An Bình',
      'An Hòa',
      'Bình Đa',
      'Bửu Hòa',
      'Bửu Long',
      'Hiệp Hòa',
      'Hóa An',
      'Hố Nai',
      'Long Bình',
      'Long Bình Tân',
      'Phước Tân',
      'Quang Vinh',
      'Quyết Thắng',
      'Tam Hiệp',
      'Tam Hòa',
      'Tân Biên',
      'Tân Hạnh',
      'Tân Hòa',
      'Tân Hiệp',
      'Tân Mai',
      'Tân Phong',
      'Tân Tiến',
      'Tân Vạn',
      'Thanh Bình',
      'Thống Nhất',
      'Trảng Dài',
      'Trung Dũng',
    ],
    'Thủ Dầu Một': [
      'Phú Cường',
      'Phú Hòa',
      'Phú Lợi',
      'Phú Thọ',
      'Hiệp Thành',
      'Phú Mỹ',
      'Chánh Nghĩa',
      'Định Hòa',
      'Hòa Phú',
      'Phú Tân',
      'Tân An',
      'Tương Bình Hiệp',
    ],
    'Nha Trang': [
      'Vĩnh Hải',
      'Vĩnh Phước',
      'Vĩnh Lương',
      'Vĩnh Ngọc',
      'Vĩnh Thạnh',
      'Vĩnh Trường',
      'Vĩnh Hòa',
      'Vĩnh Hiệp',
      'Vĩnh Thái',
      'Phước Long',
      'Phước Tân',
      'Phước Hải',
      'Phước Hòa',
      'Phước Tiến',
      'Phước Hải',
      'Lộc Thọ',
      'Phước Hòa',
      'Ngọc Hiệp',
      'Vĩnh Hòa',
      'Xương Huân',
      'Vạn Thắng',
      'Vạn Thạnh',
      'Phương Sài',
      'Phương Sơn',
      'Phước Hòa',
      'Phước Long',
      'Phước Tân',
      'Phước Tiến',
      'Phước Hải',
      'Lộc Thọ',
      'Ngọc Hiệp',
      'Vĩnh Hòa',
      'Xương Huân',
      'Vạn Thắng',
      'Vạn Thạnh',
      'Phương Sài',
      'Phương Sơn',
    ],
    // Các quận/huyện Hà Nội còn lại
    'Tây Hồ': [
      'Phú Thượng',
      'Nhật Tân',
      'Tứ Liên',
      'Quảng An',
      'Xuân La',
      'Yên Phụ',
      'Bưởi',
      'Thụy Khuê',
    ],
    'Long Biên': [
      'Ngọc Thụy',
      'Giang Biên',
      'Đức Giang',
      'Việt Hưng',
      'Gia Thụy',
      'Ngọc Lâm',
      'Phúc Lợi',
      'Bồ Đề',
      'Sài Đồng',
      'Long Biên',
      'Thạch Bàn',
      'Phúc Đồng',
      'Cự Khối',
      'Nghĩa Đô',
    ],
    'Nam Từ Liêm': [
      'Cầu Diễn',
      'Xuân Phương',
      'Phương Canh',
      'Mỹ Đình 1',
      'Mỹ Đình 2',
      'Tây Mỗ',
      'Mễ Trì',
      'Phú Đô',
      'Đại Mỗ',
      'Trung Văn',
    ],
    'Bắc Từ Liêm': [
      'Thượng Cát',
      'Liên Mạc',
      'Đông Ngạc',
      'Đức Thắng',
      'Thụy Phương',
      'Tây Tựu',
      'Xuân Đỉnh',
      'Xuân Tảo',
      'Minh Khai',
      'Cổ Nhuế 1',
      'Cổ Nhuế 2',
      'Phú Diễn',
      'Phúc Diễn',
    ],
    'Hà Đông': [
      'La Khê',
      'Phú La',
      'Phúc La',
      'Hà Cầu',
      'Yên Nghĩa',
      'Kiến Hưng',
      'Phú Lãm',
      'Phú Lương',
      'Dương Nội',
      'Đồng Mai',
      'Biên Giang',
      'Yết Kiêu',
      'Văn Quán',
      'Phúc La',
      'Nguyễn Trãi',
      'Quang Trung',
      'La Khê',
      'Vạn Phúc',
      'Yên Nghĩa',
    ],
    // Các quận TP.HCM còn lại
    'Quận 4': [
      'Phường 1',
      'Phường 2',
      'Phường 3',
      'Phường 4',
      'Phường 5',
      'Phường 6',
      'Phường 8',
      'Phường 9',
      'Phường 10',
      'Phường 12',
      'Phường 13',
      'Phường 14',
      'Phường 15',
      'Phường 16',
      'Phường 18',
    ],
    'Quận 5': [
      'Phường 1',
      'Phường 2',
      'Phường 3',
      'Phường 4',
      'Phường 5',
      'Phường 6',
      'Phường 7',
      'Phường 8',
      'Phường 9',
      'Phường 10',
      'Phường 11',
      'Phường 12',
      'Phường 13',
      'Phường 14',
    ],
    'Quận 6': [
      'Phường 1',
      'Phường 2',
      'Phường 3',
      'Phường 4',
      'Phường 5',
      'Phường 6',
      'Phường 7',
      'Phường 8',
      'Phường 9',
      'Phường 10',
      'Phường 11',
      'Phường 12',
      'Phường 13',
      'Phường 14',
    ],
    'Quận 8': [
      'Phường 1',
      'Phường 2',
      'Phường 3',
      'Phường 4',
      'Phường 5',
      'Phường 6',
      'Phường 7',
      'Phường 8',
      'Phường 9',
      'Phường 10',
      'Phường 11',
      'Phường 12',
      'Phường 13',
      'Phường 14',
      'Phường 15',
      'Phường 16',
    ],
    'Quận 9': [
      'Hiệp Phú',
      'Tăng Nhơn Phú A',
      'Tăng Nhơn Phú B',
      'Phước Long B',
      'Phước Long A',
      'Tân Phú',
      'Phước Bình',
      'Phú Hữu',
      'Thảo Điền',
      'An Phú',
      'An Khánh',
      'Bình Trưng Đông',
      'Bình Trưng Tây',
      'Cát Lái',
      'Thạnh Mỹ Lợi',
      'An Lợi Đông',
      'Thủ Thiêm',
      'Long Bình',
      'Long Thạnh Mỹ',
      'Long Phước',
      'Phước Bình',
      'Hiệp Phú',
    ],
    'Quận 10': [
      'Phường 1',
      'Phường 2',
      'Phường 3',
      'Phường 4',
      'Phường 5',
      'Phường 6',
      'Phường 7',
      'Phường 8',
      'Phường 9',
      'Phường 10',
      'Phường 11',
      'Phường 12',
      'Phường 13',
      'Phường 14',
      'Phường 15',
    ],
    'Quận 11': [
      'Phường 1',
      'Phường 2',
      'Phường 3',
      'Phường 4',
      'Phường 5',
      'Phường 6',
      'Phường 7',
      'Phường 8',
      'Phường 9',
      'Phường 10',
      'Phường 11',
      'Phường 12',
      'Phường 13',
      'Phường 14',
      'Phường 15',
      'Phường 16',
    ],
    'Quận 12': [
      'Thạnh Lộc',
      'Thạnh Xuân',
      'Thạnh Đông',
      'Thạnh Mỹ',
      'Tân Chánh Hiệp',
      'An Phú Đông',
      'Tân Thới Hiệp',
      'Tân Thới Nhất',
      'Trung Mỹ Tây',
      'Tân Hưng Thuận',
      'Đông Hưng Thuận',
      'Tân Thới Nhất',
      'Hiệp Thành',
      'Thới An',
    ],
    'Tân Phú': [
      'Tân Sơn Nhì',
      'Tây Thạnh',
      'Sơn Kỳ',
      'Tân Quy',
      'Tân Thành',
      'Phú Thọ Hòa',
      'Phú Thạnh',
      'Phú Trung',
      'Hòa Thạnh',
      'Hiệp Tân',
      'Tân Thới Hòa',
      'Phú Hòa Đông',
      'Tân Hưng',
    ],
    'Phú Nhuận': [
      'Phường 1',
      'Phường 2',
      'Phường 3',
      'Phường 4',
      'Phường 5',
      'Phường 6',
      'Phường 7',
      'Phường 8',
      'Phường 9',
      'Phường 10',
      'Phường 11',
      'Phường 12',
      'Phường 13',
      'Phường 14',
      'Phường 15',
    ],
    'Bình Tân': [
      'An Lạc',
      'An Lạc A',
      'Bình Hưng Hòa',
      'Bình Hưng Hòa A',
      'Bình Hưng Hòa B',
      'Bình Trị Đông',
      'Bình Trị Đông A',
      'Bình Trị Đông B',
      'Tân Tạo',
      'Tân Tạo A',
      'Tân Tạo B',
      'Tân Tạo C',
      'Tân Tạo D',
      'Tân Tạo E',
      'Tân Tạo F',
    ],
    'Củ Chi': [
      'Tân Phú Trung',
      'Tân Thông Hội',
      'Phước Vĩnh An',
      'Phước Hiệp',
      'An Nhơn Tây',
      'Nhuận Đức',
      'Phạm Văn Cội',
      'Phú Hòa Đông',
      'Trung Lập Thượng',
      'Trung Lập Hạ',
      'Tân An Hội',
      'Phước Thạnh',
      'Thái Mỹ',
      'Tân Thạnh Tây',
      'Hòa Phú',
      'Tân Thạnh Đông',
      'Bình Mỹ',
      'Tân Phú Trung',
      'Tân Thông Hội',
      'Phước Vĩnh An',
      'Phước Hiệp',
    ],
    'Hóc Môn': [
      'Tân Hiệp',
      'Đông Thạnh',
      'Tân Thới Nhì',
      'Thới Tam Thôn',
      'Xuân Thới Sơn',
      'Tân Xuân',
      'Xuân Thới Đông',
      'Trung Chánh',
      'Xuân Thới Thượng',
      'Bà Điểm',
      'Tân Thới Hiệp',
      'Nhị Bình',
      'Đông Thạnh',
      'Tân Thới Nhì',
      'Thới Tam Thôn',
      'Xuân Thới Sơn',
      'Tân Xuân',
      'Xuân Thới Đông',
      'Trung Chánh',
      'Xuân Thới Thượng',
      'Bà Điểm',
    ],
    'Bình Chánh': [
      'Tân Túc',
      'Bình Chánh',
      'Tân Quý Tây',
      'Vĩnh Lộc A',
      'Vĩnh Lộc B',
      'Bình Lợi',
      'Lê Minh Xuân',
      'Tân Nhựt',
      'Tân Kiên',
      'Bình Hưng',
      'Phong Phú',
      'An Phú Tây',
      'Hưng Long',
      'Đa Phước',
      'Tân Quý Đông',
      'Bình Chánh Đông',
      'Bình Chánh Tây',
      'Tân Túc',
      'Bình Chánh',
    ],
    'Nhà Bè': [
      'Nhà Bè',
      'Hiệp Phước',
      'Phước Kiển',
      'Phước Lộc',
      'Nhơn Đức',
      'Phú Xuân',
      'Long Thới',
      'Hiệp Phước',
    ],
    'Cần Giờ': [
      'Cần Thạnh',
      'Bình Khánh',
      'Tam Thôn Hiệp',
      'An Thới Đông',
      'Thạnh An',
      'Long Hòa',
      'Lý Nhơn',
      'Tân Thạnh',
      'Đông Hòa',
      'Tân Thạnh',
    ],
    // Các quận Đà Nẵng còn lại
    'Ngũ Hành Sơn': [
      'Mỹ An',
      'Khuê Mỹ',
      'Hòa Hải',
      'Hòa Quý',
      'Hòa Phát',
      'Hòa Thọ Tây',
      'Hòa Thọ Đông',
      'Hòa Xuân',
    ],
    'Liên Chiểu': [
      'Hòa Hiệp Bắc',
      'Hòa Hiệp Nam',
      'Hòa Khánh Bắc',
      'Hòa Khánh Nam',
      'Hòa Minh',
      'Hòa Phát',
      'Hòa Thọ Tây',
      'Hòa Thọ Đông',
      'Hòa Xuân',
    ],
    'Cẩm Lệ': [
      'Hòa Thọ Đông',
      'Hòa Thọ Tây',
      'Hòa Xuân',
      'Hòa Phát',
      'Hòa An',
      'Hòa Thọ',
      'Hòa Phước',
      'Hòa Khánh',
    ],
    'Hòa Vang': [
      'Hòa Bắc',
      'Hòa Châu',
      'Hòa Khương',
      'Hòa Liên',
      'Hòa Ninh',
      'Hòa Phong',
      'Hòa Phú',
      'Hòa Phước',
      'Hòa Sơn',
      'Hòa Tiến',
      'Hòa Phước',
    ],
    // Các quận Cần Thơ còn lại
    'Ô Môn': [
      'Châu Văn Liêm',
      'Thới Hòa',
      'Thới Long',
      'Long Hưng',
      'Thới An',
      'Trường Lạc',
      'Thới Thạnh',
      'Tân Hưng',
      'Thuận An',
      'Trường Lạc',
    ],
    'Bình Thủy': [
      'Bình Thủy',
      'Trà An',
      'Trà Nóc',
      'Thới An Đông',
      'An Thới',
      'Bùi Hữu Nghĩa',
      'Long Hòa',
      'Long Tuyền',
      'Thới An',
      'Trà Nóc',
    ],
    'Cái Răng': [
      'Lê Bình',
      'Hưng Phú',
      'Hưng Thạnh',
      'Ba Láng',
      'Thường Thạnh',
      'Phú Thứ',
      'Tân Phú',
      'Phú Thứ',
      'Tân Phú',
    ],
    'Thốt Nốt': [
      'Thốt Nốt',
      'Thới Thuận',
      'Thuận An',
      'Tân Lộc',
      'Trung Nhứt',
      'Thạnh Hòa',
      'Trung Kiên',
      'Tân Hưng',
      'Thuận Hưng',
      'Thanh An',
      'Thanh Thới',
    ],
    'Vĩnh Thạnh': [
      'Vĩnh Bình',
      'Thạnh Mỹ',
      'Vĩnh Thạnh',
      'Thạnh Quới',
      'Vĩnh Trinh',
      'Thạnh Lộc',
      'Vĩnh Thạnh',
    ],
    'Cờ Đỏ': [
      'Thới Hưng',
      'Cờ Đỏ',
      'Thới Hưng',
      'Thới Đông',
      'Thới Xuân',
      'Trung Hưng',
      'Trung Thạnh',
      'Trung An',
      'Đông Hiệp',
      'Đông Thắng',
      'Thới Lai',
      'Trường Xuân',
      'Trường Xuân A',
      'Trường Xuân B',
      'Xuân Thắng',
    ],
    'Phong Điền': [
      'Nhơn Ái',
      'Giai Xuân',
      'Tân Thới',
      'Trường Long',
      'Mỹ Khánh',
      'Nhơn Nghĩa',
      'Nhơn Nghĩa',
    ],
    'Thới Lai': [
      'Thới Lai',
      'Thới Thạnh',
      'Tân Thạnh',
      'Xuân Thắng',
      'Đông Bình',
      'Đông Thuận',
      'Thới Tân',
      'Trường Thắng',
      'Định Môn',
      'Trường Thành',
      'Tân Thạnh',
      'Xuân Thắng',
    ],
    // Các quận Hải Phòng còn lại
    'Hồng Bàng': [
      'Minh Khai',
      'Trại Chuối',
      'Hùng Vương',
      'Quang Trung',
      'Trần Hưng Đạo',
      'Phạm Hồng Thái',
      'Bạch Đằng',
      'Quán Toan',
      'Hùng Vương',
      'Sở Dầu',
      'Thượng Lý',
      'Hạ Lý',
      'Minh Khai',
      'Trại Chuối',
      'Quang Trung',
      'Lam Sơn',
      'An Biên',
      'Trần Nguyên Hãn',
      'Hồng Bàng',
      'Máy Chai',
      'Máy Tơ',
      'Vạn Mỹ',
    ],
    'Ngô Quyền': [
      'Máy Chai',
      'Máy Tơ',
      'Vạn Mỹ',
      'Cầu Tre',
      'Lạch Tray',
      'Đằng Giang',
      'Đổng Quốc Bình',
      'Cầu Đất',
      'Lạch Tray',
      'Đằng Giang',
      'Đổng Quốc Bình',
      'Cầu Đất',
      'Gia Viên',
      'Cầu Tre',
      'Lạch Tray',
      'Đằng Giang',
      'Đổng Quốc Bình',
      'Cầu Đất',
      'Gia Viên',
      'Cầu Tre',
    ],
    'Lê Chân': [
      'An Hải',
      'An Hải Tây',
      'An Hải Đông',
      'Nam Hải',
      'Tràng Cát',
      'Đằng Hải',
      'Đằng Lâm',
      'Cát Bi',
      'Tràng Minh',
      'Đông Hải 1',
      'Đông Hải 2',
      'Nam Hải',
      'Tràng Cát',
      'Đằng Hải',
      'Đằng Lâm',
      'Cát Bi',
      'Tràng Minh',
      'Đông Hải 1',
      'Đông Hải 2',
    ],
    'Hải An': [
      'Đông Hải',
      'Nam Hải',
      'Tràng Cát',
      'Đằng Hải',
      'Đằng Lâm',
      'Cát Bi',
      'Tràng Minh',
      'Đông Hải 1',
      'Đông Hải 2',
      'Nam Hải',
      'Tràng Cát',
    ],
    'Kiến An': [
      'Quán Trữ',
      'Lãm Hà',
      'Đồng Hòa',
      'Bắc Sơn',
      'Nam Sơn',
      'Tràng Minh',
      'Đông Hải',
      'Phù Liễn',
      'Tràng Minh',
      'Đông Hải',
      'Phù Liễn',
    ],
    'Đồ Sơn': [
      'Vạn Hương',
      'Minh Đức',
      'Đồ Sơn',
      'Ngọc Xuyên',
      'Hợp Đức',
      'Tân Thành',
      'Đa Phúc',
      'Ngọc Xuyên',
      'Hợp Đức',
      'Tân Thành',
      'Đa Phúc',
    ],
    'Dương Kinh': [
      'Anh Dũng',
      'Đa Phúc',
      'Hải Thành',
      'Hòa Nghĩa',
      'Hưng Đạo',
      'Tân Thành',
      'Anh Dũng',
      'Đa Phúc',
      'Hải Thành',
      'Hòa Nghĩa',
      'Hưng Đạo',
      'Tân Thành',
    ],
    // Thêm một số quận/huyện quan trọng khác
    'Long Khánh': [
      'Xuân An',
      'Xuân Bình',
      'Xuân Hòa',
      'Xuân Lập',
      'Xuân Tân',
      'Xuân Thạnh',
      'Xuân Trung',
      'Xuân Vinh',
      'Suối Tre',
      'Bảo Vinh',
      'Bàu Sen',
      'Bàu Trâm',
      'Hàng Gòn',
    ],
    'Dầu Tiếng': [
      'Dầu Tiếng',
      'Minh Hòa',
      'Minh Thạnh',
      'Minh Tân',
      'Long Hòa',
      'Long Tân',
      'Phước Hòa',
      'Phước Vĩnh',
      'Thanh An',
      'Thanh Tuyền',
      'Định An',
      'Định Hiệp',
      'Định Thành',
      'Tân Lập',
      'Tân Thành',
    ],
    'Bến Cát': [
      'Mỹ Phước',
      'Tân Định',
      'Thới Hòa',
      'Hòa Lợi',
      'Tân Bình',
      'Bến Cát',
      'Tân Uyên',
      'Tân Vĩnh Hiệp',
      'Thạnh Phước',
      'An Điền',
      'An Tây',
      'Phú An',
      'Cây Trường II',
      'Lai Uyên',
      'Tân Hưng',
    ],
    'Dĩ An': [
      'Dĩ An',
      'Tân Bình',
      'Tân Đông Hiệp',
      'Bình An',
      'Bình Thắng',
      'Đông Hòa',
      'An Bình',
      'An Thạnh',
      'Lái Thiêu',
      'An Sơn',
      'Bình Chuẩn',
      'Thuận Giao',
      'An Phú',
      'Hưng Định',
      'An Thạnh',
      'Bình Nhâm',
      'Lái Thiêu',
      'An Sơn',
      'Bình Chuẩn',
      'Thuận Giao',
      'An Phú',
      'Hưng Định',
    ],
    'Thuận An': [
      'Lái Thiêu',
      'Bình Nhâm',
      'An Thạnh',
      'Bình Hòa',
      'An Sơn',
      'Bình Chuẩn',
      'Thuận Giao',
      'An Phú',
      'Hưng Định',
      'Vĩnh Phú',
      'Tân Đông Hiệp',
      'Đông Hòa',
      'An Bình',
      'Bình An',
      'Bình Thắng',
    ],
    // Thêm phường/xã cho các quận/huyện Hà Nội còn lại
    'Thanh Xuân': [
      'Khương Đình',
      'Khương Mai',
      'Khương Trung',
      'Kim Giang',
      'Nguyễn Trãi',
      'Nhân Chính',
      'Phương Liệt',
      'Thanh Xuân Bắc',
      'Thanh Xuân Nam',
      'Thanh Xuân Trung',
      'Thượng Đình',
    ],
    'Sóc Sơn': [
      'Bắc Sơn',
      'Đông Xuân',
      'Đức Hòa',
      'Hiền Ninh',
      'Hồng Kỳ',
      'Kim Lũ',
      'Mai Đình',
      'Nam Sơn',
      'Phú Cường',
      'Phù Linh',
      'Phù Lỗ',
      'Quang Tiến',
      'Sóc Sơn',
      'Tân Dân',
      'Tân Hưng',
      'Tân Minh',
      'Thanh Xuân',
      'Tiên Dược',
      'Trung Giã',
      'Việt Long',
      'Xuân Giang',
      'Xuân Thu',
    ],
    'Đông Anh': [
      'Bắc Hồng',
      'Cổ Loa',
      'Đại Mạch',
      'Đông Anh',
      'Đông Hội',
      'Dục Tú',
      'Hải Bối',
      'Kim Chung',
      'Kim Nỗ',
      'Liên Hà',
      'Mai Lâm',
      'Nam Hồng',
      'Nguyên Khê',
      'Tầm Xá',
      'Thụy Lâm',
      'Tiên Dương',
      'Uy Nỗ',
      'Vân Hà',
      'Vân Nội',
      'Việt Hùng',
      'Vĩnh Ngọc',
      'Võng La',
      'Xuân Canh',
      'Xuân Nộn',
    ],
    'Gia Lâm': [
      'Bát Tràng',
      'Cổ Bi',
      'Đa Tốn',
      'Đặng Xá',
      'Đình Xuyên',
      'Đông Dư',
      'Dương Hà',
      'Dương Quang',
      'Dương Xá',
      'Kiêu Kỵ',
      'Kim Lan',
      'Kim Sơn',
      'Lệ Chi',
      'Ninh Hiệp',
      'Phù Đổng',
      'Phú Thị',
      'Trâu Quỳ',
      'Yên Thường',
      'Yên Viên',
    ],
    'Mê Linh': [
      'Chi Đông',
      'Chu Phan',
      'Đại Thịnh',
      'Hoàng Kim',
      'Kim Hoa',
      'Liên Mạc',
      'Mê Linh',
      'Quang Minh',
      'Tam Đồng',
      'Thạch Đà',
      'Thanh Lâm',
      'Tiền Phong',
      'Tiến Thắng',
      'Tiến Thịnh',
      'Tráng Việt',
      'Tự Lập',
      'Văn Khê',
      'Vạn Yên',
    ],
    'Ba Vì': [
      'Ba Trại',
      'Ba Vì',
      'Cẩm Lĩnh',
      'Cam Thượng',
      'Châu Sơn',
      'Chu Minh',
      'Cổ Đô',
      'Đông Quang',
      'Đồng Thái',
      'Khánh Thượng',
      'Minh Châu',
      'Minh Quang',
      'Phong Vân',
      'Phú Châu',
      'Phú Cường',
      'Phú Đông',
      'Phú Phương',
      'Phú Sơn',
      'Sơn Đà',
      'Tản Hồng',
      'Tản Lĩnh',
      'Thái Hòa',
      'Thuần Mỹ',
      'Thụy An',
      'Tiên Phong',
      'Tòng Bạt',
      'Vân Hòa',
      'Vạn Thắng',
      'Yên Bài',
    ],
    'Phúc Thọ': [
      'Cẩm Đình',
      'Hát Môn',
      'Hiệp Thuận',
      'Liên Hiệp',
      'Long Xuyên',
      'Ngọc Tảo',
      'Phúc Hòa',
      'Phụng Thượng',
      'Phương Độ',
      'Sen Chiểu',
      'Tam Hiệp',
      'Tam Thuấn',
      'Thanh Đa',
      'Thọ Lộc',
      'Thượng Cốc',
      'Tích Giang',
      'Trạch Mỹ Lộc',
      'Vân Côn',
      'Vân Nam',
      'Vân Phúc',
      'Xuân Phú',
    ],
    'Đan Phượng': [
      'Đan Phượng',
      'Đồng Tháp',
      'Hạ Mỗ',
      'Hồng Hà',
      'Liên Hà',
      'Liên Hồng',
      'Liên Trung',
      'Phùng',
      'Phương Đình',
      'Song Phượng',
      'Tân Hội',
      'Tân Lập',
      'Thọ An',
      'Thọ Xuân',
      'Thượng Mỗ',
      'Trung Châu',
    ],
    'Hoài Đức': [
      'An Khánh',
      'An Thượng',
      'Cát Quế',
      'Đắc Sở',
      'Đông La',
      'Đức Giang',
      'Đức Thượng',
      'Dương Liễu',
      'Kim Chung',
      'La Phù',
      'Lại Yên',
      'Minh Khai',
      'Sơn Đồng',
      'Song Phương',
      'Tiền Yên',
      'Trạm Trôi',
      'Vân Canh',
      'Vân Côn',
      'Yên Sở',
    ],
    'Quốc Oai': [
      'Cấn Hữu',
      'Cộng Hòa',
      'Đại Thành',
      'Đồng Quang',
      'Đông Xuân',
      'Đông Yên',
      'Hòa Thạch',
      'Liệp Tuyết',
      'Nghĩa Hương',
      'Ngọc Liệp',
      'Ngọc Mỹ',
      'Phú Cát',
      'Phú Mãn',
      'Phượng Cách',
      'Sài Sơn',
      'Tân Hòa',
      'Tân Phú',
      'Thạch Thán',
      'Tuyết Nghĩa',
      'Yên Sơn',
    ],
    'Thạch Thất': [
      'Bình Phú',
      'Bình Yên',
      'Cẩm Yên',
      'Cần Kiệm',
      'Canh Nậu',
      'Chàng Sơn',
      'Đại Đồng',
      'Đồng Trúc',
      'Dị Nậu',
      'Hạ Bằng',
      'Hương Ngải',
      'Hữu Bằng',
      'Kim Quan',
      'Lại Thượng',
      'Liên Quan',
      'Phú Kim',
      'Phùng Xá',
      'Tân Xã',
      'Thạch Hòa',
      'Thạch Xá',
      'Tiến Xuân',
      'Yên Bình',
      'Yên Trung',
    ],
    'Chương Mỹ': [
      'Chúc Sơn',
      'Đại Yên',
      'Đồng Lạc',
      'Đồng Phú',
      'Đông Phương Yên',
      'Đông Sơn',
      'Hoàng Diệu',
      'Hoàng Văn Thụ',
      'Hồng Phong',
      'Hợp Đồng',
      'Hữu Văn',
      'Lam Điền',
      'Mỹ Lương',
      'Nam Phương Tiến',
      'Ngọc Hòa',
      'Phú Nam An',
      'Phú Nghĩa',
      'Phụng Châu',
      'Quảng Bị',
      'Tân Tiến',
      'Thanh Bình',
      'Thượng Vực',
      'Thụy Hương',
      'Thủy Xuân Tiên',
      'Tiên Phương',
      'Tốt Động',
      'Trần Phú',
      'Trung Hòa',
      'Trường Yên',
      'Văn Võ',
      'Xuân Mai',
    ],
    'Thanh Oai': [
      'Bích Hòa',
      'Bình Minh',
      'Cao Dương',
      'Cao Viên',
      'Cự Khê',
      'Dân Hòa',
      'Đỗ Động',
      'Hồng Dương',
      'Kim An',
      'Kim Thư',
      'Liên Châu',
      'Mỹ Hưng',
      'Phương Trung',
      'Tam Hưng',
      'Tân Ước',
      'Thanh Cao',
      'Thanh Mai',
      'Thanh Thùy',
      'Thanh Văn',
      'Xuân Dương',
    ],
    'Thường Tín': [
      'Chương Dương',
      'Dũng Tiến',
      'Duyên Thái',
      'Hà Hồi',
      'Hiền Giang',
      'Hòa Bình',
      'Hồng Vân',
      'Khánh Hà',
      'Lê Lợi',
      'Liên Phương',
      'Minh Cường',
      'Nghiêm Xuyên',
      'Nguyễn Trãi',
      'Nhị Khê',
      'Ninh Sở',
      'Quất Động',
      'Tân Minh',
      'Thắng Lợi',
      'Thống Nhất',
      'Thư Phú',
      'Tiền Phong',
      'Tự Nhiên',
      'Văn Bình',
      'Vạn Điểm',
      'Văn Phú',
      'Vân Tảo',
    ],
    'Phú Xuyên': [
      'Bạch Hạ',
      'Châu Can',
      'Chuyên Mỹ',
      'Đại Thắng',
      'Đại Xuyên',
      'Hoàng Long',
      'Hồng Minh',
      'Hồng Thái',
      'Khai Thái',
      'Minh Tân',
      'Nam Phong',
      'Nam Tiến',
      'Phú Minh',
      'Phú Túc',
      'Phú Yên',
      'Phúc Tiến',
      'Phượng Dực',
      'Quang Lãng',
      'Quang Trung',
      'Sơn Hà',
      'Tân Dân',
      'Thụy Phú',
      'Tri Thủy',
      'Tri Trung',
      'Văn Hoàng',
      'Văn Nhân',
      'Vân Từ',
    ],
    'Ứng Hòa': [
      'Cao Thành',
      'Đại Cường',
      'Đại Hùng',
      'Đội Bình',
      'Đông Lỗ',
      'Đồng Tân',
      'Đồng Tiến',
      'Hòa Lâm',
      'Hòa Nam',
      'Hòa Phú',
      'Hoa Sơn',
      'Hòa Xá',
      'Hồng Quang',
      'Kim Đường',
      'Liên Bạt',
      'Lưu Hoàng',
      'Minh Đức',
      'Phù Lưu',
      'Phương Tú',
      'Quảng Phú Cầu',
      'Sơn Công',
      'Tảo Dương Văn',
      'Trầm Lộng',
      'Trung Tú',
      'Trường Thịnh',
      'Vạn Điểm',
      'Vân Đình',
      'Viên An',
      'Viên Nội',
    ],
    'Mỹ Đức': [
      'An Mỹ',
      'An Phú',
      'An Tiến',
      'Bột Xuyên',
      'Đại Hưng',
      'Đại Nghĩa',
      'Đốc Tín',
      'Đồng Tâm',
      'Hồng Sơn',
      'Hợp Thanh',
      'Hùng Tiến',
      'Hương Sơn',
      'Lê Thanh',
      'Mỹ Thành',
      'Phù Lưu Tế',
      'Phúc Lâm',
      'Phùng Xá',
      'Phương Đông',
      'Tuy Lai',
      'Vạn Kim',
      'Xuy Xá',
    ],
  };

  static List<String> getDistrictsByProvince(String province) {
    return districts[province] ?? [];
  }

  static List<String> getWardsByDistrict(String district) {
    return wards[district] ?? [];
  }
}

